logging:
  level:
    tech.oldhorse: debug
server:
  port: 8080

spring:
  application:
    name: shop
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  freemarker:
    check-template-location: false
springdoc:
  api-docs:
    enabled: true
#    dev-url: http://localhost:8081
#    prod-url: http://localhost:8081
common-sequence:
  snowflakeWorkNode: 1