spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      database: 0
      host: ${REDIS_HOST:localhost}
      port: 6379
      timeout: 10s
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
wx:
  miniapp:
    configs:
      - appid: 123
        secret: 123
        token: 123
        aesKey: 123
        msgDataFormat: JSON
sa-token:
  token-name: satoken
  timeout: 2592000
  active-timeout: -1
  is-share: true
  token-style: uuid
  is-log: true
