logging:
  level:
    tech.oldhorse: debug
server:
  port: 8080

spring:
  application:
    name: shop
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  freemarker:
    check-template-location: false
mybatis:
  mapper-locations: classpath:mapper/*DAO.xml
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
springdoc:
  api-docs:
    enabled: true
#    dev-url: http://localhost:8081
#    prod-url: http://localhost:8081
